# Generated by Django 5.2.5 on 2025-08-10 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('alert_type', models.CharField(choices=[('threshold', 'Threshold'), ('duration', 'Duration')], max_length=10)),
                ('condition', models.CharField(choices=[('gt', '>'), ('lt', '<')], max_length=2)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('duration_hours', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriggeredAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('current_price', models.FloatField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_alerts', to='api.alert')),
            ],
        ),
    ]
